#ifndef _CONSTANTS_

#define _CONSTANTS_

#define UPDATE_SLICE_TIMER 15
#define SCALE_FACTOR 1.2
#define NUM_OF_LAYERS 1
//#define CROSS_LAYER     (NUM_OF_LAYERS>1)?NUM_OF_LAYERS-1:-1
#define SELECTION_LAYER std::max(0,NUM_OF_LAYERS-2)
#define ACTIVE 1
#define DEFAULT_DRAW_SIZE 2
#define MIN_DRAW_SIZE 1
#define MAX_DRAW_SIZE 50
#define NOT_ACTIVE 0



#endif